"""add_production_tracking_fields

Revision ID: 1476a717a5cd
Revises: 
Create Date: 2026-02-11 16:17:54.139804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1476a717a5cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('batch', 'finalized_at',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    op.add_column('id_request', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('id_request', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # op.alter_column('id_request', 'source',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            nullable=False,
    #            existing_server_default=sa.text("'odoo'"))
    # op.alter_column('id_request', 'requester_name',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=True)
    # op.alter_column('id_request', 'transferred_to_queue',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # op.alter_column('id_request', 'transfer_note',
    #            existing_type=sa.TEXT(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_id_request_batch_id'), 'id_request', ['batch_id'], unique=False)
    # op.create_foreign_key(None, 'id_request', 'batch', ['batch_id'], ['id'])
    # op.alter_column('manufacturing_order', 'date_start',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manufacturing_order', 'date_start',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'id_request', type_='foreignkey')
    op.drop_index(op.f('ix_id_request_batch_id'), table_name='id_request')
    op.alter_column('id_request', 'transfer_note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('id_request', 'transferred_to_queue',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('id_request', 'requester_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('id_request', 'source',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'odoo'"))
    op.drop_column('id_request', 'finished_at')
    op.drop_column('id_request', 'started_at')
    op.alter_column('batch', 'finalized_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
