"""feat_adiciona_campo_product_name_manufacturing_order

Revision ID: 3de1fc2dac5e
Revises: g1h2i3j4k5l6
Create Date: 2026-04-20 10:45:54.718044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de1fc2dac5e'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elesys_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elesys_consumption_date'))

    op.drop_table('elesys_consumption')
    with op.batch_alter_table('andon_call', schema=None) as batch_op:
        batch_op.alter_column('root_cause_detail',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('action_taken',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # Conversão de VARCHAR → enum loglevel requer:
    # 1. Dropar o DEFAULT (que é 'INFO'::varchar, incompatível com o enum)
    # 2. Alterar o tipo com USING explícito
    # 3. Recolocar o DEFAULT já como valor do enum
    op.execute("ALTER TABLE esp_device_logs ALTER COLUMN level DROP DEFAULT")
    op.execute("ALTER TABLE esp_device_logs ALTER COLUMN level TYPE loglevel USING level::loglevel")
    op.execute("ALTER TABLE esp_device_logs ALTER COLUMN level SET DEFAULT 'INFO'::loglevel")

    with op.batch_alter_table('firmware_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_firmware_versions_created_at'))
        batch_op.drop_index(batch_op.f('idx_firmware_versions_is_stable'))
        batch_op.drop_index(batch_op.f('idx_firmware_versions_version'))

    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_manufacturing_order_product_name'), ['product_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturing_order_product_name'))
        batch_op.drop_column('product_name')

    with op.batch_alter_table('firmware_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_firmware_versions_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('idx_firmware_versions_is_stable'), ['is_stable'], unique=False)
        batch_op.create_index(batch_op.f('idx_firmware_versions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('esp_device_logs', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.Enum('INFO', 'WARN', 'ERROR', name='loglevel'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))

    with op.batch_alter_table('andon_call', schema=None) as batch_op:
        batch_op.alter_column('action_taken',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('root_cause_detail',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('elesys_consumption',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('code', postgresql.ENUM('T58', 'T96', name='elesyscode'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('elesys_consumption_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('elesys_consumption_pkey'))
    )
    with op.batch_alter_table('elesys_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elesys_consumption_date'), ['date'], unique=False)

    # ### end Alembic commands ###
