"""feat: adiciona product_category_id em manufacturing_order

Revision ID: 55345983c5ea
Revises: 49c3c5e95b24
Create Date: 2026-05-06 16:33:09.492462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55345983c5ea'
down_revision: Union[str, None] = '49c3c5e95b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door_label_preset_favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_door_label_preset_favorite_preset_id'))
        batch_op.drop_index(batch_op.f('ix_door_label_preset_favorite_username'))

    op.drop_table('door_label_preset_favorite')
    with op.batch_alter_table('door_label_preset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_door_label_preset_created_by'))
        batch_op.drop_index(batch_op.f('ix_door_label_preset_is_shared'))
        batch_op.drop_index(batch_op.f('ix_door_label_preset_is_system'))
        batch_op.drop_index(batch_op.f('ix_door_label_preset_name'))

    op.drop_table('door_label_preset')
    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_manufacturing_order_product_category_id'), ['product_category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturing_order_product_category_id'))
        batch_op.drop_column('product_category_id')

    op.create_table('door_label_preset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('equipment_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('columns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('door_label_preset_pkey'))
    )
    with op.batch_alter_table('door_label_preset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_door_label_preset_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_door_label_preset_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_door_label_preset_is_shared'), ['is_shared'], unique=False)
        batch_op.create_index(batch_op.f('ix_door_label_preset_created_by'), ['created_by'], unique=False)

    op.create_table('door_label_preset_favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['door_label_preset.id'], name=op.f('door_label_preset_favorite_preset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('door_label_preset_favorite_pkey'))
    )
    with op.batch_alter_table('door_label_preset_favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_door_label_preset_favorite_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_door_label_preset_favorite_preset_id'), ['preset_id'], unique=False)

    # ### end Alembic commands ###
