"""feat_adiciona_tabelas_device_label_door_label_terminal_label

Revision ID: 6845f97487d8
Revises: bd9d7e42dbf9
Create Date: 2026-04-24 15:17:31.399813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6845f97487d8'
down_revision: Union[str, None] = 'bd9d7e42dbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('device_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_label_device_tag'), ['device_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_label_mo_id'), ['mo_id'], unique=False)

    op.create_table('door_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('door_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_door_label_mo_id'), ['mo_id'], unique=False)

    op.create_table('terminal_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('terminal_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wire_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminal_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminal_label_mo_id'), ['mo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_label_terminal_number'), ['terminal_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminal_label_terminal_number'))
        batch_op.drop_index(batch_op.f('ix_terminal_label_mo_id'))

    op.drop_table('terminal_label')
    with op.batch_alter_table('door_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_door_label_mo_id'))

    op.drop_table('door_label')
    with op.batch_alter_table('device_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_label_mo_id'))
        batch_op.drop_index(batch_op.f('ix_device_label_device_tag'))

    op.drop_table('device_label')
    # ### end Alembic commands ###
