"""feat_adiciona_campo_ax_code_manufacturing_order

Revision ID: 751202eac0a4
Revises: 3de1fc2dac5e
Create Date: 2026-04-23 08:39:09.734062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '751202eac0a4'
down_revision: Union[str, None] = '3de1fc2dac5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ax_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_manufacturing_order_ax_code'), ['ax_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturing_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturing_order_ax_code'))
        batch_op.drop_column('ax_code')

    # ### end Alembic commands ###
