"""feat: adiciona tabelas esp_devices e esp_device_logs

Revision ID: 9d897bb0f491
Revises: b38a1f5c609d
Create Date: 2026-03-31 12:08:52.857063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d897bb0f491'
down_revision: Union[str, None] = 'b38a1f5c609d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
