"""feat(db): analytics tracking models

Revision ID: b38a1f5c609d
Revises: 1476a717a5cd
Create Date: 2026-03-23 10:13:29.943642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b38a1f5c609d'
down_revision: Union[str, None] = '1476a717a5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('id_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('iniciado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('concluido_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('entregue_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aprovado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_id_request_aprovado_em'), ['aprovado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_id_request_concluido_em'), ['concluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_id_request_entregue_em'), ['entregue_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_id_request_iniciado_em'), ['iniciado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_id_request_solicitado_em'), ['solicitado_em'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('id_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_request_solicitado_em'))
        batch_op.drop_index(batch_op.f('ix_id_request_iniciado_em'))
        batch_op.drop_index(batch_op.f('ix_id_request_entregue_em'))
        batch_op.drop_index(batch_op.f('ix_id_request_concluido_em'))
        batch_op.drop_index(batch_op.f('ix_id_request_aprovado_em'))
        batch_op.drop_column('aprovado_em')
        batch_op.drop_column('entregue_em')
        batch_op.drop_column('concluido_em')
        batch_op.drop_column('iniciado_em')
        batch_op.drop_column('solicitado_em')

    # ### end Alembic commands ###
