"""feat: adiciona campo location em esp_devices

Revision ID: b9a922a58e25
Revises: f45dafaf98ee
Create Date: 2026-04-06 16:34:11.208208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9a922a58e25'
down_revision: Union[str, None] = 'f45dafaf98ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esp_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esp_devices', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
