"""feat_adiciona_tabelas_printer_e_print_job

Revision ID: bd9d7e42dbf9
Revises: 751202eac0a4
Create Date: 2026-04-24 08:57:39.396830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd9d7e42dbf9'
down_revision: Union[str, None] = '751202eac0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printer_name'), ['name'], unique=False)

    op.create_table('print_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('id_request_id', sa.Uuid(), nullable=True),
    sa.Column('label_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zpl_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='printjobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_request_id'], ['id_request.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_job_id_request_id'), ['id_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_printer_id'), ['printer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_status'), ['status'], unique=False)
        batch_op.create_index('ix_print_job_status_printer_id', ['status', 'printer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_index('ix_print_job_status_printer_id')
        batch_op.drop_index(batch_op.f('ix_print_job_status'))
        batch_op.drop_index(batch_op.f('ix_print_job_printer_id'))
        batch_op.drop_index(batch_op.f('ix_print_job_id_request_id'))

    op.drop_table('print_job')
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printer_name'))

    op.drop_table('printer')
    # ### end Alembic commands ###
